version: '3.4'

services:
  microservicea.api:
    image: ${DOCKER_REGISTRY-}microserviceaapi
    build:
      context: .
      dockerfile: Microservices/MicroserviceA/src/MicroserviceA.API/Dockerfile

  microserviceb.api:
    image: ${DOCKER_REGISTRY-}microservicebapi
    build:
      context: .
      dockerfile: Microservices/MicroserviceB/src/MicroserviceB.API/Dockerfile

  microservicec.api:
    image: ${DOCKER_REGISTRY-}microservicecapi
    build:
      context: .
      dockerfile: Microservices/MicroserviceC/src/MicroserviceC.API/Dockerfile

  microserviced.api:
    image: ${DOCKER_REGISTRY-}microservicedapi
    build:
      context: .
      dockerfile: Microservices/MicroserviceD/src/MicroserviceD.API/Dockerfile

networks:
  default:
    external:
      name: microservicesnet


